### PR TITLE
Add modality/tags charts, analytics page

### PR DESCRIPTION
**Pull request by liamocn**
## Related issues

#14 

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose

This adds two more chart types to the dashboard chart and a dropdown to toggle between them. An analytics page containing all charts has been added
 
#### Does this introduce a major change?
- [x] Yes
- [ ] No

## Implementation Detail

The way charts work on the portal had been reworked using the official React bindings for Highcharts.

### CODE REVIEW

**Comment by liamocn** [comment]
Yes those bubble graphs move around a bit when they appear. That's by design but I can look into making them appear more static. You can view the names of the keywords by hovering your mouse over the bubbles. I'll look at how I can make that more obvious. Maybe if those charts were bigger overall it would be easier to see.

**Comment by liamocn** [comment]
@cmadjar Hmm, this library that we use for the charts doesn't seem to be capable of doing any of that. I'll have to research new libraries and see if there's one that can be implemented like this.

**Comment by cmadjar** [comment]
@liamocn feedbacks from today's demo:
- Functional links on the bubble if possible to have that
- Remove outer light circle and extend the graph to use more of the white space
- Modify title to something like: `Dataset Modalities Representation By Keywords`/ `Pipeline Representation By Tags`

Hopefully I did not miss any...

**Review by cmadjar — CHANGES_REQUESTED** [review]
@liamocn  thank you for updating this! A few comments:

- there is a lot of white space around the bubble charts (for both the dashboard and the analytics page). Is there a way to decrease the white space?
Screen Shot 2020-10-20 at 2 11 04 PM
- Change titles of graphs to:
  - Dataset Modalities Representation By Keywords
  - Pipeline Representation By Tags
- Given that the title of the graph already mention that the graph represents dataset modalities, maybe the bubble legend is not necessary?
- for the chart, I see histology (2) and Histology (3) but when you click on the bubbles, you get 5 results in the search page => I think histology and Histology should be only one bubble in the chart to match the behaviour of the search page (bubble should not be case sensitive to the tags)

Thank you! Let me know when ready for another round of testing/review.

**Review by cmadjar — APPROVED** [review]
Thank you @liamocn !

**Pull request merged**
