### PR TITLE
Update the contact us form to the new and improved contact us link

### PR DESCRIPTION
**Pull request by cmadjar**
A new contact us form has been created for the portal. The new link to the form is: https://docs.google.com/forms/d/e/1FAIpQLSe01Po0tXd11JDzYF9Jtfpj1eReiSPDXCEknpxK_6NEGL6D2A/viewform

#376

### CODE REVIEW

**Comment by cmadjar** [comment]
Problem: because the google form includes file uploads, it cannot be embedded into the portal. 

Two solutions:
1) modify the contact us link to open a new tab with the google form directly so users can upload screenshots (then the contact_us.html page should be removed)
2) modify the contact form itself to remove the file upload questions so it can be embedded into the portal contact us page

Email sent to Jessica and Patrick for a final decision.

**Comment by cmadjar** [comment]
Solution 2 has been selected so the file upload function of the form has been removed so that it can renders in the website

**Comment by cmadjar** [comment]
@liamocn ready for review and merge when you get back. Thanks!

**Review by liamocn — APPROVED** [review]
Looks good!

**Pull request merged**
