### PR TITLE
Datasets update unsign datalad

### PR DESCRIPTION
**Pull request by xlecours**
## Related issues
https://github.com/CONP-PCNO/conp-portal/issues/96

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose
install conp-datasets using datalad python library. It also populate database fields from information avalaible via the DATS.json file in the datasets.
 
#### Does this introduce a major change?
- [x] Yes
- [ ] No

## Implementation Detail
- Adding Datalad in requirements.txt
- Datasets logo will not default to `default_dataset.jpeg` until the logo can be obtained from the DATS.json
- Many fields in the Dataset table have been removed because they could not be populated.
- The DatasetsStats table is removed because 
    1. It was missing a foreign key to the Dataset table (sqlite do not allow to ALTER table to add foreign key)
    2. Most of the fields could not be populated. 

to test this, 
 1. `flask db upgrade`
 2. delete everyting in the Dataset table,
 3. `flask update_datasets` -- Datalad will clone the conp-datasets repo and recursively install its submodules.

### CODE REVIEW

**Comment by liamocn** [comment]
Hi, I noticed the tests are failing on this. I checked out the branch to see what's up and it seems to be related to how datalad fetches the remote dataset.

1. Can you confirm that
` api.clone(source='http://github.com/CONP-PCNO/conp-dataset', path=datasetspath + '/conp-dataset')`
is working for you? This gets called when you run `flask seed_test_db` if the dataset doesn't exist locally.

2. There are references to DatasetStats still in the test suites. Since that's been removed from the model then those tests will have to go too.

3. You should use `pip freeze > requirements.txt` to update requirements.txt after you pip install another dependency

**Comment by xlecours** [comment]
@liamocn Thanks for the review
1. It is working on my machine. Did you run `flask db upgrade` ?
2. I wasn't aware of any tests. I'll clean them
3. I did knew that there was a way to manage requirements. I will try it.

**Comment by liamocn** [comment]
@xlecours Yeah I ran `flask db upgrade` and that's all fine. I need to investigate

**Comment by glatard** [comment]
Hi, any update on that? It would be great if that could be deployed for Brainhack MTL, as people might be adding their datasets to conp-datasets.

**Comment by xlecours** [comment]
@glatard I will be working on that today. I still need to finalize the migration part.

**Comment by xlecours** [comment]
branch renamed to `datasets_using_datalad`

**Pull request closed without merging**
