### PR TITLE
Add SPARQL UI

### PR DESCRIPTION
**Pull request by zxenia**
## Purpose
The PR adds SPARQL UI (at `/sparql`) to access Nexus sparql endpoint and run sparql queries.
The UI is provided by the [YASGUI](https://triply.cc/docs/yasgui) library.

Nexus endpoint is public, no credentials needed.
Nexus endpoint url added to the config.

## Related issues
#276

## Checklist

- [x] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Current behaviour
Currently, there is no SPARQL UI

## New behaviour
SPARQL UI can be accessed at `/sparql`
 
#### Does this introduce a major change?
- [ ] Yes
- [x] No

## Implementation Detail
The css `height: fit-content` is not working in Mozilla. When tab **Response** is active the div with the raw json response overflows the footer. Need to fix it with some cross-browser value.

The `/sparql` view is not linked anywhere yet in the navigation bar.

## Queries for testing

The query returns the datasets URIs in Nexus and titles
```
PREFIX sdo: <https://schema.org/>
SELECT ?dataset ?title
WHERE {?dataset a sdo:Dataset.
       ?dataset sdo:name ?title.
      }
LIMIT 20
```

### CODE REVIEW

**Comment by cmadjar** [comment]
@zxenia based on the comments this morning, do you want to add some example queries to that PR before we merge it or should we merge it?

**Comment by zxenia** [comment]
@cmadjar The proper examples will take more, for now, we can have this interface merged. But the only issue now is that it's not linked anywhere on the navbar yet, so to access it the user has to type the actual address `/sparql`.
I don't know where we can add a link. Do you have ideas?

**Comment by cmadjar** [comment]
@zxenia indeed, the link. Ooops... The most logical place to me would be in the data search page (some sort of link for "Advanced Querying With Nexus" that would redirect to the sparql page).

I feel the whole search/filter section of the data search page could be redesigned/improved. That could be something done in collaboration with @3design to try to see how the filters could be reorganized but that is more long term than short term I guess. 
 @3design Thoughts on this?

**Comment by cmadjar** [comment]
@zxenia I am going through my notes of the past few weeks. If I remember correctly, all that is left for this PR is to create the link to the Nexus page on the data search page. Something like a `Advanced Search (NEXUS)`.

Correct? Thanks!

**Comment by zxenia** [comment]
Hi @cmadjar yes, correct. I think last time we decide that the link can be added to the dataset search page and also decided to add a banner/text that SPARQL search is experimental. This is my bad I haven't done it yet.

**Comment by zxenia** [comment]
Hi @cmadjar It's done now. The screenshots below show how it would look.

sparql-experimental-mode
sparql-link-to-dataset-search

**Comment by cmadjar** [comment]
@zxenia could the link to the advanced search be above the results table? Maybe below the Search box?

Thanks!

**Pull request merged**
