### PR TITLE
Monitoring/dataset element

### PR DESCRIPTION
**Pull request by mathdugre**
## Related issues

CONP-PCNO/conp-dataset#259

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose

Those changes allow an easier tracking of each dataset status. Therefore, a user can know that a dataset might be experiencing issue at a certain time.

## Current behaviour

There is no monitoring feature displaying the status of a dataset.

## New behaviour

Allow users, to see if there are issues a dataset is currently experiencing issues.
Show a "shield badge" for each dataset element indicating its status.
 
#### Does this introduce a major change?
- [ ] Yes
- [x] No

## Implementation Detail

1. Retrieve the latest artifacts from CircleCI.
1.1 To speed up retrieval, artifact results are cached with a 4 hours timeout.
2. Parse the artifacts.
* If dataset not found in test results, mark as CircleCI status.
* If all tests succeed for dataset, mark as CircleCI status.
* If some tests are skipped and others are successful, mark as CircleCI status.
* Otherwise, mark as CircleCI status

### CODE REVIEW

**Comment by cmadjar** [comment]
@mathdugre There are conflicts with the base branch. Would you mind rebasing? Thank you!

**Comment by mathdugre** [comment]
@cmadjar, I'm currently waiting for CONP-PCNO/conp-dataset#311 to be merged before rebasing. 

As of right now, the test suite often time out and prevents to obtain the tests results. This would make this PR to display a _warning_ badge next to most datasets; which is not desirable.
This is fixed in CONP-PCNO/conp-dataset#311.

**Comment by glatard** [comment]
@mathdugre there are still conflicts here, do you think you could fix them?

**Comment by glatard** [comment]
Hi @liamocn, I'm not sure why this doesn't pass the tests but it looks like it's not related to the PR, do you confirm?

**Comment by liamocn** [comment]
> 
> 
> Hi @liamocn, I'm not sure why this doesn't pass the tests but it looks like it's not related to the PR, do you confirm?

Yes the pipeline tests are failing travis for other PRs too. I've tested this and it looks great, thanks @mathdugre !

**Pull request merged**
