### PR TITLE
Alan's feedback on the terms of use

### PR DESCRIPTION
**Pull request by cmadjar**
---
This PR updates the terms of use with Alan's corrections.
---

## Checklist
- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

#### Does this introduce a major change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by jbpoline** [comment]
Ironing text, no need for 2nd review

**Comment by cmadjar** [comment]
@jbpoline I am not sure to understand why you closed this PR? Is something wrong with it?

**Comment by jbpoline** [comment]
sorry - meant to merge - need coffee....

**Comment by cmadjar** [comment]
hahaha, no worries. Go get your coffee ;)

**Pull request merged**
