### PR TITLE
Addition of a number of views and number of downloads sort by functionality

### PR DESCRIPTION
**Pull request by cmadjar**
This adds the sort by views and downloads functionalities to the search pages. 

Screen Shot 2021-11-08 at 5 08 19 PM

## Related issues

#508

### CODE REVIEW

**Comment by cmadjar** [comment]
@tkkuehn Would you have time to review and test this? Thank you!

**Comment by cmadjar** [comment]
@tkkuehn I am going to fix the download analytics number for the pipeline in this PR after discussing this in the CONP dev call. I will tag you when ready for review and test.

Sorry for the delay..

**Comment by tkkuehn** [comment]
Ok no problem!

**Comment by cmadjar** [comment]
@tkkuehn OK. Ready now :). Thank you!!

**Review by tkkuehn — CHANGES_REQUESTED** [review]
Just a couple of typos but otherwise looks good to me, feel free to merge when those are fixed! (I don't know if there's a good way to populate the analytics table locally without a Matomo instance, so I couldn't test whether the sorting actually works, but the code looks fine to me and the options show up locally.)

**Comment by cmadjar** [comment]
Thank you @tkkuehn :). I pulled the code on portal-dev.conp.ca if you want to test it there? It has the analytics set up.

**Review by tkkuehn — APPROVED** [review]
Okay tried it out and it seems to work well!

**Comment by cmadjar** [comment]
Thank you :-)

**Pull request merged**
