### PR TITLE
Add cbrain logo in relevent pipeline elements

### PR DESCRIPTION
**Pull request by joeyzhou98**
## Related issues

Add link to online platform where pipeline is installed #66

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose

Sets the pipeline element image logo route in routes.py in server before sending to client and add condition that if cbrain is in url, the logo will be a cbrain logo instead of a globe icon

## Current behaviour

No cbrain logo even if url leads to cbrain website in pipeline elements

## New behaviour

A cbrain logo will be present if the url contains the string "cbrain" in pipeline elements
 
#### Does this introduce a major change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by joeyzhou98** [comment]
@glatard that is weird, I see mine correctly

image
image

**Comment by glatard** [comment]
This seems to be due to the images being stored in `svg` (not sure why): converting to `png` should work.

**Comment by joeyzhou98** [comment]
@glatard could you try again on firefox?

**Comment by glatard** [comment]
Yes, it works perfectly now!

**Comment by glatard** [comment]
@paiva, you might want to review this before it's merged.

**Comment by paiva** [comment]
@glatard Yes, it will be reviewed this afternoon

**Pull request merged**
