### PR TITLE
Sort updates

### PR DESCRIPTION
**Pull request by liamocn**
## Related issues

#252 #253 #260 

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose

Fixes sorting issues with dataset search. Sorting is now possible in ascending and descending orders.
 
#### Does this introduce a major change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by cmadjar** [comment]
@liamocn Another thing I just noticed. In the modality filter, histology is duplicated (histology vs Histology). There should be only one of them available in the filter and it should be able to filter for both cases.

Same thing for file format (minc/MINC should refer to the same thing)

**Comment by liamocn** [comment]
> 
> 
> @liamocn thank you for the updates.
> 
> A few notes regarding the modality and file format filters:
> 
>     * Modality:
>       
>       * eeg should be displayed as EEG
>       * t1w should be displayed as T1W
>       * mri should be displayed as MRI
>       * fmri should be displayed as fMRI
> 
>     * File format
>       
>       * there is still duplication of file formats (csv vs .csv, nifti present twice and many others)
>       * also, I think it would be best to display the name of the format with their official way of writing them
>         
>         * nifti => NIfTI (note the lower case f in this one)
>         * minc => MINC
>         * dicom => DICOM
>         * tsv => TSV
>         * csv => CSV
>         * json => JSON
>         * and so on
> 

@cmadjar It's difficult to determine any of this on the frontend since there's a certain amount of variation in the datasets themselves. Ideally, keys for modality and format would be unique and consistent so they can be properly indexed. If they had a display name or similar associated with them, which would be the readable form, even better

**Comment by cmadjar** [comment]
@liamocn Thank you for your reply. These can be dealt with later on. 

However, did you see my last comment about the selection of formats not being displayed the same way as the selection of modality is displayed? (a.k.a. it goes up the screen instead of being displayed below the filter)

image

**Comment by liamocn** [comment]
@cmadjar Yes, I'll see if I can resolve that. Thanks.

**Pull request merged**
