### PR TITLE
Process CONP datasets in CBRAIN , Issue 348

### PR DESCRIPTION
**Pull request by mandana-mazaheri**
---
Title: Change the style of CBrain button
title: 'Feature implementation for issue #<348>'
labels: enhancement
assignees: ''Mandana Mazaheri"

---

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose
<To reduce the size of CBrain button and apply dynamic resizing for that >

## Current behavior
<The CBrain button was too large and was in the same division as the next column so whenever the size of the window changed these two columns would merge or go out of the border>

## New behavior
<The CBrain button is smaller and its size is automatically compatible with page size>
 
#### Does this introduce a major change?
- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@mandana-mazaheri see attached comment to modify the CBRAIN button so that it has a fixed size when reducing the window.

For the padding, you will need to modify line 109 to the following:
```
      <div className="row pr-4">
```
(addition of the px-4 bootstrap to ensure there is padding on the left and right side of the card which will avoid the buttons to overlap with the card border.)

Finally, maybe we can set a time together where we go through your npm install because the builds need to be generated for your PR.

**Comment by cmadjar** [comment]
@mandana-mazaheri have you had a chance to work on this?

**Comment by mandana-mazaheri** [comment]
Hi Cecile, thanks for following up.

Yes I applied what you mentioned before but the button size changed to the
larger size than the current one. I attached the photo of that. I tried
different px sizes but didn’t change anything.

I’m working more on the dashboard of pipeline executions now. But I’ll try
to figure why it happens to the button here.

**Comment by mandana-mazaheri** [comment]
I’m working on another laptop (the linux one) for the portal and that’s why
I used my phone. 😁

**Comment by mandana-mazaheri** [comment]
To reduce the size of CBRAIN button and apply the requested changes

**Comment by cmadjar** [comment]
@mandana-mazaheri thank you for the changes. Could you please generate the npm build files and add them to the PR?

```
npm install
npm run build
```

**Comment by cmadjar** [comment]
Closing in favour of #471 as discussed with @mandana-mazaheri offline.

**Pull request closed without merging**
