### PR TITLE
[UPDATE] Refactored base page and fragments templates + styled dashbo…

### PR DESCRIPTION
**Pull request by candicecz**
---
name: Updated page styles
about: Updated the CONP portal UI with bootstrap.
title: 'Updated page styling'
labels: enhancement
assignees: ''

---

## Related issues
Establish CONP style guide CSS #75

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose
This PR is meant to fix styling issues within the portal using the elements previously created in the styleguide. 

## Current behaviour
There are currently some style bugs when it comes to layout. There is also no standard page template.

## New behaviour
This PR uses app/templates/base_public.html as a base template for all pages consisting of a navigation, sidebar and footer. It also imports the components from the styleguide into the pages. This PR does not address admin views of the portal.

 
#### Does this introduce a major change?
- [x] Yes
- [ ] No

## Implementation Detail
The UI elements are created using CSS and Bootstrap and are fully responsive according to Derek's designs. I also changed some elements inside the react components.

### CODE REVIEW

**Comment by jbpoline** [comment]
Hi - is there a quick guide on how to locally install and test ?

**Comment by shots47s** [comment]
Yes, the installation instructions are in the main READme.md

**Comment by jbpoline** [comment]
cool - thanks

**Comment by shots47s** [comment]
The coverage went down, that was the unsuccessful check, but we are not sure exactly how to test the CSS yet, so I will take that.  @JB, were you able to test it.  I would like to merge as this is blocking.

**Pull request merged**
