### PR TITLE
Add a CBRAIN button in the dataset card

### PR DESCRIPTION
**Pull request by mandana-mazaheri**
---

about: Processing available datasets in CBRAIN
title: Process CONP datasets in CBRAIN issue #<348>'
labels: enhancement
assignees: ''

---

## Related issues

#63

## Checklist

- [ ] **DO** Unit tests pass.
- [ ] **DO** If new feature, created unit test.

## Purpose
Process CONP datasets in CBRAIN, add a column as process for each dataset, and place the CBRAIN button in that column

#### Does this introduce a major change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@mandana-mazaheri Thank you for submitting the PR!

Two comments:
- The CBRAIN button looks squeezed horizontally in the dataset card. Would it be possible to unsqueeze it so that it renders the same as in the pipeline's search page?
Screen Shot 2021-04-28 at 9 13 45 AM

- you need to run `npm install` + `npm run build` and commit the changed files. Otherwise the changes are not compiled and won't be pulled on the portal when we merge

**Comment by mandana-mazaheri** [comment]
Cecile, I got some screenshots which shows it works properly on my local version, but although I built it by 'npm run build' it wont work on the server. Would the reason be the built files generated in 'conp-portal/app/static/lib/conp-react/umd/' that I have no permission to commit them?
Screenshot from 2021-04-28 10-35-23
Screenshot from 2021-04-28 10-35-35

**Comment by cmadjar** [comment]
Hi Mandana,

This is what I get on Safari, Chrome and Firefox when I checkout your branch and run `npm run build`

- Safari
safari

- Chrome
chrome

- Firefox
firefox

Not sure why we get totally different things... :S

**Comment by mandana-mazaheri** [comment]
oh it's bad, I'll work on it, I am really confused about what the problem is

**Review by cmadjar — APPROVED** [review]
LGTM 👍

**Pull request merged**
